# Generated by Django 2.2.2 on 2019-06-23 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_call_begings', models.TimeField(default=datetime.time(17, 0))),
                ('on_call_ends', models.TimeField(default=datetime.time(9, 0))),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
            options={
                'verbose_name': 'ProjectSettings',
                'verbose_name_plural': 'ProjectSettingss',
            },
        ),
        migrations.CreateModel(
            name='Overtimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_date_start', models.DateTimeField()),
                ('overtime_date_end', models.DateTimeField()),
                ('operation', models.CharField(choices=[('ON', 'On call'), ('OUT', 'Call out'), ('OVER', 'Overtime')], default='ON', max_length=4)),
                ('time_spend_weekday', models.DurationField(blank=True, null=True)),
                ('time_spend_weekend', models.DurationField(blank=True, null=True)),
                ('time_spend_night', models.DurationField(blank=True, null=True)),
                ('time_spend_holiday', models.DurationField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('overtimes_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Project')),
            ],
            options={
                'verbose_name': 'Overtimes',
                'verbose_name_plural': 'Overtimess',
            },
        ),
    ]
