# Generated by Django 2.2.2 on 2019-06-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='follow_holidays',
            field=models.BooleanField(default=True),
        ),
    ]
