# Generated by Django 2.2.2 on 2019-06-25 15:02

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectsettings_follow_holidays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsettings',
            name='country',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='follow_holidays',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='on_call_begings',
        ),
        migrations.RemoveField(
            model_name='projectsettings',
            name='on_call_ends',
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(default=5, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='follow_holidays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='on_call_begings',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='project',
            name='on_call_ends',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
