# Generated by Django 2.2.2 on 2019-06-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='on_call_begings',
            new_name='on_call_begins',
        ),
    ]
