# Generated by Django 2.2.2 on 2019-06-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190628_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimes',
            old_name='who_saved',
            new_name='owner',
        ),
    ]
